# Generated by Django 4.1.5 on 2023-01-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='carousel.png', upload_to='images/carousel')),
                ('title', models.CharField(max_length=200)),
                ('car_url', models.CharField(max_length=200)),
            ],
        ),
    ]
