# Generated by Django 4.1.5 on 2023-01-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='title',
        ),
        migrations.AddField(
            model_name='carousel',
            name='title_first_part',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carousel',
            name='title_second_part',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
