# Generated by Django 4.1.5 on 2023-01-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haead_text_ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ad_url', models.CharField(max_length=400)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
