# Generated by Django 4.1.5 on 2023-01-14 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_haead_text_ads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Haead_text_ads',
            new_name='HaeadTextAd',
        ),
    ]
