# Generated by Django 4.1.5 on 2023-01-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_haead_text_ads_haeadtextad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HaeadTextAd',
            new_name='HeadTextAd',
        ),
    ]
