# Generated by Django 4.1.5 on 2023-01-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_haeadtextad_headtextad'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAdDayly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='daily_ad.png', upload_to='images/daily_ad')),
                ('title', models.CharField(max_length=100)),
                ('ad_url', models.CharField(max_length=400)),
                ('position', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='L', max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Home Ad Dayly',
            },
        ),
    ]
