# Generated by Django 4.1.5 on 2023-01-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homeaddayly'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAdDealTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='deal_time_ad.png', help_text='Please use our recommended dimensions: 568px x 503px, 250 KB MAX', upload_to='images/deal_time')),
                ('title', models.CharField(max_length=120)),
                ('supplier', models.CharField(choices=[('S', 'Salem'), ('P', 'Pizza'), ('H', 'Hamburger'), ('D', 'Dunner')], default='S', max_length=5)),
                ('supplier_url', models.CharField(max_length=400)),
                ('price', models.DecimalField(decimal_places=2, default='00', max_digits=100)),
                ('discount', models.DecimalField(decimal_places=2, default='00', max_digits=100)),
                ('deal_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
