# Generated by Django 4.1.5 on 2023-01-14 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homeaddealtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeaddealtime',
            name='deal_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
