# Generated by Django 4.1.5 on 2023-01-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homeaddealtime_deal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeaddealtime',
            name='supplier',
            field=models.CharField(choices=[('Salem', 'Salem'), ('Pizza', 'Pizza'), ('Hamburger', 'Hamburger'), ('Dunner', 'Dunner')], default='Salem', max_length=50),
        ),
    ]
