# Generated by Django 4.1.5 on 2023-01-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homeaddealtime_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAdMiddleBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='middle_banner.png', help_text='Please use our recommended dimensions: 768px x 450px, 250 KB MAX', upload_to='images/middle_banner')),
                ('title', models.CharField(max_length=120)),
                ('ad_url', models.CharField(max_length=400)),
                ('image_position', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('M', 'Middle')], default='L', max_length=10)),
            ],
        ),
    ]
