# Generated by Django 4.1.5 on 2023-01-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_homeadmiddlebanner_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAdSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='middle_banner.png', help_text='Please use our recommended dimensions: 756px x 332px, 250 KB MAX', upload_to='images/ads_supplier')),
                ('title_first_part', models.CharField(max_length=50)),
                ('title_second_part', models.CharField(blank=True, max_length=50)),
                ('supplier_url', models.CharField(max_length=400)),
                ('image_position', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('M', 'Middle')], default='L', max_length=10)),
            ],
        ),
    ]
